### ISSUE TITLE
A question about parameters update

### ISSUE THREAD

**Issue by kjw11** [biomedia-mira/masf#12]
Hi, sorry for bothering.

I notiticed that in your method, the D_tr updatas the model parameters at first, then calculate Global loss and Local loss on updated model. But I did't understand what role the update operation is play in your method? From my understanding, the update operation in MAML method is used to simulate the finetuning (adaptation) process when implementing on few-shot learning. Is my understanding wrong?

Thanks for you attention and your time.

**Comment by carrenD** [comment]
Hi the model update on D_tr is supervised learning on task loss. Thanks!
