### ISSUE TITLE
Usage for medical image segmentation

### ISSUE THREAD

**Issue by neerakara** [biomedia-mira/masf#13]
Is the image segmentation code supposed to work after replacing the construct_alexnet_weights() and forward_alexnex() functions by construct_unet_weights() and forward_unet(). Or do other changes need to be made? I am running into a few errors:
1. For instance, the forward_unet() function returns 4 outputs, while the line after the comment "# Obtaining the conventional task loss on meta-train" expects 2 outputs from the forward function.
2. The forward_unet() function does not expect the 'reuse' parameter as input.
3. Several 'shape must be rank 2 but is rank 4' errors.

**Comment by carrenD** [comment]
Hi Please see here for medical image analysis: https://github.com/liuquande/SAML
