### ISSUE TITLE
Release deeper network code

### ISSUE THREAD

**Issue by tbuikr** [biomedia-mira/masf#9]
Thanks for sharing the repo!

Do you have plan to release the deeper network model as the report in table 4? Thanks

**Comment by carrenD** [comment]
yes, we have plan, still under construction, kept busy being interrupted by many stuff...

**Comment by hosseinshn** [comment]
Any updates on this issue?

**Comment by carrenD** [comment]
Hi, please refer our another work: https://github.com/liuquande/SAML 
where the is method is applied to a deeper network on a real-world medcial application. 
Thanks!
